---
name: 'CI'
on:
  push:
    branches:
      - 'master'
    tags:
      - '*'

jobs:
  luacheck:
    name: 'Luacheck'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: 'actions/checkout@v1'
        with:
          fetch-depth: 1
      - name: 'Install LuaRocks'
        run: |
          sudo apt install luarocks
      - name: 'Install Luacheck'
        run: |
          luarocks install --local luacheck
      - name: 'Run Luacheck'
        run: |
          ${HOME}/.luarocks/bin/luacheck .
  release:
    name: 'Release Addon'
    runs-on: 'ubuntu-latest'
    needs: 'luacheck'
    steps:
      - uses: 'actions/checkout@v1'
        with:
          fetch-depth: 1
      # WoWI-ID is specified as an argument due to WoWI not supporting both
      # Classic and Retail under a single addon, and how the release script
      # parses the TOC.
      #
      # Release script arguments:
      #   -d Skip upload
      #   -l Skip localisation replacements
      #   -u Use Unix line-endings
      #   -g Classic version
      #   -w WoWInterface ID
      #
      # Release Classic Addon on both CurseForge and WoWInterface.
      # No WoWI Classic for the moment, see
      # https://github.com/BigWigsMods/packager/issues/33
      - name: 'Release Burning Crusade Classic Addon'
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        uses: 'BigWigsMods/packager@v1'
        with:
          args: '-l -u -g bcc -w 25276'
      - name: 'Release Classic Addon'
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        uses: 'BigWigsMods/packager@v1'
        with:
          args: '-l -u -g classic -w 25276'
      # Release Retail Addon only on WoWInterface, as CurseForge is handled
      # elsewhere.
      - name: 'Release Retail Addon'
        env:
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
        uses: 'BigWigsMods/packager@v1'
        with:
          args: '-l -u -g retail -w 25276'
